name: php-code-sniffs
services:
  php-dev:
    build:
      args: &build_args
        - PHP_VERSION=${PHP_VERSION:-8.2}
      context: ../.
      dockerfile: ./.docker/Dockerfile
      target: dev_image
    configs:
      - source: phpunit-cs
        target: /usr/src/cs-test/phpunit.xml
      - source: xdebug
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    container_name: ${COMPOSE_PROJECT_NAME}-dev
    image: max-antipin/${COMPOSE_PROJECT_NAME}:dev
    restart: unless-stopped
    tty: true
    volumes:
      - ../.:/usr/src/app/
      - ../AntipinCS/:/usr/src/cs-test/src/Standards/AntipinCS/:ro
      - ../var/coverage-report/:/tmp/coverage-report/
configs:
  phpunit-cs:
    file: ./phpunit.9.xml
  xdebug:
    file: ./xdebug.ini
